# Generated by Django 3.0.3 on 2020-04-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='description',
        ),
        migrations.AddField(
            model_name='camera',
            name='path',
            field=models.CharField(default='/mnt/cameras/', max_length=100),
            preserve_default=False,
        ),
    ]
